Fix foreign key constraint error when trying to delete a `Recipe`
If you have `on_delete=DO_NOTHING`, there will be an IntegrityError when
you try to delete a `Recipe` object since the foreign key of
`RecipeHadIngredient` still points to that object.

For example, PostgreSQL raises an error message like so:

<<<

django.db.utils.IntegrityError: update or delete on table
"recipe_recipe" violates foreign key constraint
"kitchen_recipehading_recipe_id_id_f551dd49_fk_recipe_re" on table
"kitchen_recipehadingredient"

DETAIL:  Key (id)=(29) is still referenced from table
"kitchen_recipehadingredient".

>>>

Also, this was my fault. I thought that "DO_NOTHING" meant a
`RecipeHadIngredient` object would not be affected by deletions of
`Recipe` objects.

But hey, at least I got to write a unit test :)